'''
  ******************************************************************************************
      Assembly:                BudgetPy
      Filename:                Schema.py
      Author:                  Terry D. Eppler
      Created:                 05-31-2023

      Last Modified By:        Terry D. Eppler
      Last Modified On:        06-01-2023
  ******************************************************************************************
  <copyright file="Schema.py" company="Terry D. Eppler">

     This is a Federal Budget, Finance, and Accounting application.
     Copyright ©  2024  Terry Eppler

     Permission is hereby granted, free of charge, to any person obtaining a copy
     of this software and associated documentation files (the “Software”),
     to deal in the Software without restriction,
     including without limitation the rights to use,
     copy, modify, merge, publish, distribute, sublicense,
     and/or sell copies of the Software,
     and to permit persons to whom the Software is furnished to do so,
     subject to the following conditions:

     The above copyright notice and this permission notice shall be included in all
     copies or substantial portions of the Software.

     THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
     INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
     FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
     DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
     ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
     DEALINGS IN THE SOFTWARE.

     You can contact me at:  terryeppler@gmail.com or eppler.terry@epa.gov

  </copyright>
  <summary>
    Schema.py
  </summary>
  ******************************************************************************************
  '''
from sqlalchemy import (MetaData, Table, Column, Integer, Numeric,
                        String, Float, DateTime, ForeignKey, create_engine)
from Booger import Error, ErrorDialog
from Static import Source, Provider, SQL
from datetime import datetime

metadata = MetaData( )

accounts = Table( 'Accounts', metadata,
	Column( 'AccountsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 155 ) ) )

program_projects = Table( 'ProgramProjects', metadata,
	Column( 'ProgramProjectsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 155 ) ) )

program_areas = Table( 'ProgramAreas', metadata,
	Column( 'ProgramAreasId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 155 ) ) )

allocations = Table( 'Allocations', metadata,
	Column( 'AllocationsId', Integer( ), primary_key=True ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BFY', String( 100 ) ),
	Column( 'EFY', String( 100 ) ),
	Column( 'RpioCode', String( 100 ) ),
	Column( 'RpioName', String( 100 ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 155 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 155 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'RcCode', String( 155 ) ),
	Column( 'RcName', String( 155 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 155 ) ),
	Column( 'Amount', Float ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 155 ) ),
	Column( 'ProgramAreaCode', String( 100 ) ),
	Column( 'ProgramAreaName', String( 100 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 155 ) ) )

application_tables = Table( 'ApplicationTables', metadata,
	Column( 'ApplicationTablesId', Integer( ), primary_key=True ),
	Column( 'TableName', String( 155 ) ),
	Column( 'Model', String( 155 ) ),
	Column( 'Title', String( 155 ) ) )

appropriation_documents = Table( 'AppropriationDocuments', metadata,
	Column( 'AppropriationDocumentsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'Fund', String( 155 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'AppropriationFund', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 155 ) ),
	Column( 'DocumentDate', DateTime ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BudgetingControls', String( 80 ) ),
	Column( 'PostingControls', String( 80 ) ),
	Column( 'PreCommitmentControls', String( 80 ) ),
	Column( 'CommitmentControls', String( 80 ) ),
	Column( 'ObligationControls', String( 80 ) ),
	Column( 'AccrualControls', String( 80 ) ),
	Column( 'ExpenditureControls', String( 80 ) ),
	Column( 'ExpenseControls', String( 80 ) ),
	Column( 'ReimbursementControls', String( 80 ) ),
	Column( 'ReimbursableAgreementControls', String( 80 ) ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'CarryoverOut', Float ),
	Column( 'CarryoverIn', Float ),
	Column( 'Reimbursements', Float ),
	Column( 'Recoveries', Float ) )

budget_controls = Table( 'BudgetControls', metadata,
	Column( 'BudgetControlValuesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'SecurityOrg', String( 80 ) ),
	Column( 'BudgetingTransType', String( 80 ) ),
	Column( 'PostedTransType', String( 80 ) ),
	Column( 'EstimatedReimbursableTransType', String( 80 ) ),
	Column( 'SpendingAdjustmentTransType', String( 80 ) ),
	Column( 'EstimatedRecoveriesTransType', String( 80 ) ),
	Column( 'ActualRecoveriesTransType', String( 80 ) ),
	Column( 'StategicReserveTransType', String( 80 ) ),
	Column( 'ProfLossTransType', String( 80 ) ),
	Column( 'EstimatedReimbursableSpendingOption', String( 80 ) ),
	Column( 'EstimatedReimbursableBudgetingOption', String( 80 ) ),
	Column( 'TrackAgreementLowerLevel', String( 80 ) ),
	Column( 'BudgetEstimateLowerLevel', String( 80 ) ),
	Column( 'EstimatedRecoveriesSpendingOption', String( 80 ) ),
	Column( 'EstimatedRecoveriesBudgetingOption', String( 80 ) ),
	Column( 'RecordNextLevel', String( 80 ) ),
	Column( 'RecordBudgetingMismatch', String( 80 ) ),
	Column( 'ProfitLossSpendingOption', String( 80 ) ),
	Column( 'ProfitLossBudgetingOption', String( 80 ) ),
	Column( 'RecordCarryInLowerLevel', String( 80 ) ),
	Column( 'RecordCarryInLowerLevelControl', String( 80 ) ),
	Column( 'RecordCarryInAmountControl', String( 80 ) ),
	Column( 'BudgetingControl', String( 80 ) ),
	Column( 'PostingControl', String( 80 ) ),
	Column( 'PreCommitmentSpendingControl', String( 80 ) ),
	Column( 'CommitmentSpendingControl', String( 80 ) ),
	Column( 'ObligationSpendingControl', String( 80 ) ),
	Column( 'AccrualSpendingControl', String( 80 ) ),
	Column( 'ExpenditureSpendingControl', String( 80 ) ),
	Column( 'ExpenseSpendingControl', String( 80 ) ),
	Column( 'ReimbursableSpendingControl', String( 80 ) ),
	Column( 'ReimbursableAgreementSpendingControl', String( 80 ) ),
	Column( 'FteBudgetingControl', String( 80 ) ),
	Column( 'FteSpendingControl', String( 80 ) ),
	Column( 'TransactionTypeControl', String( 80 ) ),
	Column( 'AuthorityDistributionControl', String( 80 ) ) )

budget_documents = Table( 'BudgetDocuments', metadata,
	Column( 'BudgetDocumentsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'DocumentDate', DateTime ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 155 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 155 ) ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'CarryoverOut', Float ),
	Column( 'CarryoverIn', Float ),
	Column( 'Recoveries', Float ),
	Column( 'Reimbursements', Float ) )

changes = Table( 'Changes', metadata,
	Column( 'ChangesId', Integer( ), primary_key=True ),
	Column( 'TableName', String( 155 ) ),
	Column( 'FieldName', String( 80 ) ),
	Column( 'Action', String( 80 ) ),
	Column( 'OldValue', String( 80 ) ),
	Column( 'NewValue', String( 80 ) ),
	Column( 'Time', String( 80 ) ),
	Column( 'Message', String( 155 ) ) )

monthly_outlays = Table( 'MonthlyOutlays', metadata,
	Column( 'AgencyTitle', String( 155 ) ),
	Column( 'BureauTitle', String( 80 ) ),
	Column( 'OmbAccountTitle', String( 155 ) ),
	Column( 'TreasuryAccountTitle', String( 155 ) ),
	Column( 'October', Float ),
	Column( 'November', Float ),
	Column( 'December', Float ),
	Column( 'January', Float ),
	Column( 'Feburary', Float ),
	Column( 'March', Float ),
	Column( 'April', Float ),
	Column( 'May', Float ),
	Column( 'June', Float ),
	Column( 'July', Float ),
	Column( 'August', Float ),
	Column( 'September', Float ) )

reference_tables = Table( 'ReferenceTables', metadata,
	Column( 'ReferenceTablesId', Integer( ), primary_key=True ),
	Column( 'TableName', String( 155 ) ),
	Column( 'Type', String( 80 ) ) )

query_definitions = Table( 'QueryDefinitions', metadata,
	Column( 'QueryDefinitionsId', Integer( ), primary_key=True ),
	Column( 'Name', String( 155 ) ),
	Column( 'Type', String( 80 ) ) )

reimbursable_agreements = Table( 'ReimbursableAgreements', metadata,
	Column( 'ReimbursableAgreementsId', Integer( ), primary_key=True ),
	Column( 'RPIO', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'AgreementNumber', String( 80 ) ),
	Column( 'StartDate', DateTime ),
	Column( 'EndDate', DateTime ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'DivisionName', String( 155 ) ),
	Column( 'SiteProjectCode', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'VendorCode', String( 80 ) ),
	Column( 'VendorName', String( 155 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'ULO', Float ),
	Column( 'Available', Float ) )

reimbursable_survey = Table( 'ReimbursableSurvey', metadata,
	Column( 'ReimbursableSurveyId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 155 ) ),
	Column( 'Amount', Float ) )

actuals = Table( 'Actuals', metadata,
	Column( 'ActualsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 155 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 155 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 155 ) ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'AppropriationName', String( 155 ) ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'SubAppropriationName', String( 155 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 155 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 155 ) ),
	Column( 'RpioActivityCode', String( 80 ) ),
	Column( 'RpioActivityName', String( 155 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 155 ) ),
	Column( 'ULO', Float ),
	Column( 'Obligations', Float ),
	Column( 'Balance', Float ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 155 ) ),
	Column( 'GoalCode', String( 80 ) ),
	Column( 'GoalName', String( 155 ) ),
	Column( 'ObjectiveCode', String( 80 ) ),
	Column( 'ObjectiveName', String( 155 ) ) )

status_of_funds = Table( 'StatusOfFunds', metadata,
	Column( 'StatusOfFundsId', Integer( ), primary_key=True ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 155 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 155 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 155 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 155 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 155 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 155 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 155 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 155 ) ),
	Column( 'LowerName', String( 155 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 155 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

status_of_superfund_sites = Table( 'StatusOfSuperfundSites', metadata,
	Column( 'SiteActivityId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'EpaSiteId', String( 80 ) ),
	Column( 'SiteProjectCode', String( 80 ) ),
	Column( 'SSID', String( 80 ) ),
	Column( 'ActionCode', String( 80 ) ),
	Column( 'OperableUnit', String( 80 ) ),
	Column( 'SiteProjectName', String( 80 ) ),
	Column( 'State', String( 80 ) ),
	Column( 'City', String( 80 ) ),
	Column( 'CongressionalDistrict', String( 80 ) ),
	Column( 'ProjectType', String( 80 ) ),
	Column( 'StartDate', DateTime ),
	Column( 'LastActivity', DateTime ),
	Column( 'Requested', Float ),
	Column( 'Accepted', Float ),
	Column( 'Closed', Float ),
	Column( 'Outstanding', Float ),
	Column( 'Refunded', Float ),
	Column( 'Reversal', Float ) )

status_of_appropriations = Table( 'StatusOfAppropriations', metadata,
	Column( 'StatusOfAppropriationsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'AppropriationFundCode', String( 80 ) ),
	Column( 'AppropriationFundName', String( 80 ) ),
	Column( 'Availability', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'AppropriationCreationDate', DateTime ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'AppropriationDescription', String( 80 ) ),
	Column( 'FundGroup', String( 80 ) ),
	Column( 'FundGroupName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'TransType', String( 80 ) ),
	Column( 'ActualRecoveryTransType', String( 80 ) ),
	Column( 'CommitmentSpendingControlFlag', String( 80 ) ),
	Column( 'AgreementLimit', String( 80 ) ),
	Column( 'EstimatedRecoveriesTransType', String( 80 ) ),
	Column( 'EstimatedReimbursmentsTransType', String( 80 ) ),
	Column( 'ExpenseSpendingControlFlag', String( 80 ) ),
	Column( 'ObligationSpendingControlFlag', String( 80 ) ),
	Column( 'PreCommitmentSpendingControlFlag', String( 80 ) ),
	Column( 'PostedControlFlag', String( 80 ) ),
	Column( 'PostedFlag', String( 80 ) ),
	Column( 'RecordCarryoverAtLowerLevel', String( 80 ) ),
	Column( 'ReimbursableSpendingOption', String( 80 ) ),
	Column( 'RecoveriesOption', String( 80 ) ),
	Column( 'RecoveriesSpendingOption', String( 80 ) ),
	Column( 'OriginalBudgetedAmount', Float ),
	Column( 'ApportionmentsPosted', Float ),
	Column( 'TotalAuthority', Float ),
	Column( 'TotalBudgeted', Float ),
	Column( 'TotalPostedAmount', Float ),
	Column( 'FundsWithdrawnPriorYearsAmount', Float ),
	Column( 'FundingInAmount', Float ),
	Column( 'FundingOutAmount', Float ),
	Column( 'TotalAccrualRecoveries', Float ),
	Column( 'TotalActualReimbursements', Float ),
	Column( 'TotalAgreementReimbursables', Float ),
	Column( 'TotalCarriedForwardIn', Float ),
	Column( 'TotalCarriedForwardOut', Float ),
	Column( 'TotalCommitted', Float ),
	Column( 'TotalEstimatedRecoveries', Float ),
	Column( 'TotalEstimatedReimbursements', Float ),
	Column( 'TotalExpenses', Float ),
	Column( 'TotalExpenditureExpenses', Float ),
	Column( 'TotalExpenseAccruals', Float ),
	Column( 'TotalPreCommitments', Float ),
	Column( 'UnliquidatedPreCommitments', Float ),
	Column( 'TotalObligations', Float ),
	Column( 'ULO', Float ),
	Column( 'VoidedAmount', Float ),
	Column( 'TotalUsedAmount', Float ),
	Column( 'AvailableAmount', Float ) )

status_of_supplemental_funds = Table( 'StatusOfSupplementalFunds', metadata,
	Column( 'StatusOfSupplementalFundsId', Integer( ), primary_key=True ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

status_of_jobs_act_funds = Table( 'StatusOfJobsActFunds', metadata,
	Column( 'StatusOfJobsActFundsId', Integer( ), primary_key=True ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

unliquidated_obligations = Table( 'UnliquidatedObligations', metadata,
	Column( 'UnliquidatedObligationsId', Integer( ), primary_key=True ),
	Column( 'ObligationsId', Integer( ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'ReferenceDocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'Age', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'VendorCode', String( 80 ) ),
	Column( 'VendorName', String( 80 ) ),
	Column( 'Amount', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

budgetary_resource_execution = Table( 'BudgetaryResourceExecution', metadata,
	Column( 'BudgetaryResourceExecutionId', Integer( ), primary_key=True ),
	Column( 'FiscalYear', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'LastUpdate', DateTime ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'STAT', String( 80 ) ),
	Column( 'CreditIndicator', String( 80 ) ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'LineDescription', String( 80 ) ),
	Column( 'SectionName', String( 80 ) ),
	Column( 'SectionNumber', String( 80 ) ),
	Column( 'LineType', String( 80 ) ),
	Column( 'FinancingAccounts', String( 80 ) ),
	Column( 'November', Float ),
	Column( 'January', Float ),
	Column( 'Feburary', Float ),
	Column( 'April', Float ),
	Column( 'May', Float ),
	Column( 'June', Float ),
	Column( 'August', Float ),
	Column( 'October', Float ),
	Column( 'Amount1', Float ),
	Column( 'Amount2', Float ),
	Column( 'Amount3', Float ),
	Column( 'Amount4', Float ) )

transfers = Table( 'Transfers', metadata,
	Column( 'TransfersId', Integer( ), primary_key=True ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'DocPrefix', String( 80 ) ),
	Column( 'DocType', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'ReprogrammingNumber', String( 80 ) ),
	Column( 'ControlNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'Quarter', String( 80 ) ),
	Column( 'Line', String( 80 ) ),
	Column( 'Subline', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'FromTo', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'ResourceType', String( 80 ) ),
	Column( 'Purpose', String( 80 ) ),
	Column( 'ExtendedPurpose', String( 80 ) ) )

deobligations = Table( 'Deobligations', metadata,
	Column( 'DeobligationsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'Amount', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

obligations = Table( 'Obligations', metadata,
	Column( 'ObligationsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'ReferenceDocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'Age', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'VendorCode', String( 80 ) ),
	Column( 'VendorName', String( 80 ) ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

expenditures = Table( 'Expenditures', metadata,
	Column( 'ExpendituresId', Integer( ), primary_key=True ),
	Column( 'ObligationsId', Integer( ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'ReferenceDocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'Age', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'VendorCode', String( 80 ) ),
	Column( 'VendorName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 155 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 155 ) ) )

open_commitments = Table( 'OpenCommitments', metadata,
	Column( 'OpenCommitmentsId', Integer( ), primary_key=True ),
	Column( 'ObligationsId', Integer( ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'ReferenceDocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'Age', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 155 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'VendorCode', String( 80 ) ),
	Column( 'VendorName', String( 100 ) ),
	Column( 'Amount', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

subappropriations = Table( 'SubAppropriations', metadata,
	Column( 'SubAppropriationsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

apportionment_data = Table( 'ApportionmentData', metadata,
	Column( 'ApportionmentDataId', Integer( ), primary_key=True ),
	Column( 'FiscalYear', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'TreasuryAppropriationFundSymbol', String( 80 ) ),
	Column( 'TreasuryAppropriationFundSymbolName', String( 80 ) ),
	Column( 'ApportionmentAccountCode', String( 80 ) ),
	Column( 'ApportionmentAccountName', String( 80 ) ),
	Column( 'AvailabilityType', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'ApprovalDate', DateTime ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'LineName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'MainAccount', String( 80 ) ) )

changes = Table( 'Changes', metadata,
	Column( 'TableName', String( 80 ) ),
	Column( 'FieldName', String( 80 ) ),
	Column( 'ActionType', String( 80 ) ),
	Column( 'OldValue', String( 80 ) ),
	Column( 'NewValue', String( 80 ) ),
	Column( 'ChangeDate', DateTime ),
	Column( 'Message', String( 80 ) ) )

data_rule_descriptions = Table( 'DataRuleDescriptions', metadata,
	Column( 'DataRuleDescriptionsId', Integer( ), primary_key=True ),
	Column( 'Schedule', String( 80 ) ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'RuleNumber', String( 80 ) ),
	Column( 'RuleDescription', String( 80 ) ),
	Column( 'ScheduleOrder', String( 80 ) ) )

document_control_numbers = Table( 'DocumentControlNumbers', metadata,
	Column( 'DocumentControlNumbersId', Integer( ), primary_key=True ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'DocumentPrefix', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ) )

appropriations = Table( 'Appropriations', metadata,
	Column( 'AppropriationsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

unobligated_balances = Table( 'UnobligatedBalances', metadata,
	Column( 'UnobligatedBalancesId', Integer( ), primary_key=True ),
	Column( 'BudgetYear', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'BudgetAccount', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AccountNumber', String( 80 ) ),
	Column( 'AccountName', String( 80 ) ),
	Column( 'Amount', Float ) )

funds = Table( 'Funds', metadata,
	Column( 'FundsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'ShortName', String( 80 ) ),
	Column( 'Status', String( 80 ) ),
	Column( 'StartDate', DateTime ),
	Column( 'EndDate', DateTime ),
	Column( 'SubLevelPrefix', String( 80 ) ),
	Column( 'AllocationTransferAgency', String( 80 ) ),
	Column( 'AgencyIdentifier', String( 80 ) ),
	Column( 'BeginningPeriodOfAvailability', String( 80 ) ),
	Column( 'EndingPeriodOfAvailability', String( 80 ) ),
	Column( 'MultiyearIndicator', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'SubAccount', String( 80 ) ),
	Column( 'FundCategory', String( 80 ) ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'FundGroup', String( 80 ) ),
	Column( 'NoYear', String( 80 ) ),
	Column( 'Carryover', String( 80 ) ),
	Column( 'CanceledYearSpendingAccount', String( 80 ) ),
	Column( 'ApplyAtAllLevels', String( 80 ) ),
	Column( 'BatsFund', String( 80 ) ),
	Column( 'BatsEndDate', DateTime ),
	Column( 'BatsOptionId', String( 80 ) ),
	Column( 'SecurityOrg', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'ApportionmentAccountCode', String( 80 ) ) )

fund_symbols = Table( 'FundSymbols', metadata,
	Column( 'FundSymbolsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'ApportionmentAccountCode', String( 80 ) ) )

state_organizations = Table( 'StateOrganizations', metadata,
	Column( 'StateOrganizationsId', Integer( ), primary_key=True ),
	Column( 'Name', String( 80 ) ),
	Column( 'Code', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ) )

state_grant_obligations = Table( 'StateGrantObligations', metadata,
	Column( 'StateGrantObligationsId', Integer( ), primary_key=True ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'StateCode', String( 80 ) ),
	Column( 'StateName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'Amount', Float ) )

status_of_earmarks = Table( 'StatusOfEarmarks', metadata,
	Column( 'StatusOfEarmarksId', Integer( ), primary_key=True ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

recovery_act = Table( 'RecoveryAct', metadata,
	Column( 'RecoveryActId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'Amount', Float ) )

obligation_activity = Table( 'ObligationActivity', metadata,
	Column( 'ObligationActivityId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'UnliquidatedObligations', Float ),
	Column( 'Outlays', Float ) )

deobligation_activity = Table( 'DeobligationActivity', metadata,
	Column( 'DeobligtionActivityId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'Amount', Float ) )

monthly_ledger_account_balances = Table( 'MonthlyLedgerAccountBalances', metadata,
	Column( 'MonthlyLedgerAccountBalancesId', Integer( ), primary_key=True ),
	Column( 'FiscalYear', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'LedgerAccount', String( 80 ) ),
	Column( 'LedgerName', String( 80 ) ),
	Column( 'ApportionmentAccountCode', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'TreasurySymbolName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'FiscalMonth', String( 80 ) ),
	Column( 'CreditBalance', Float ),
	Column( 'DebitBalance', Float ),
	Column( 'YearToDateAmount', Float ) )

outlays = Table( 'Outlays', metadata,
	Column( 'OutlaysId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'AppropriationName', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'MonthProcessed', String( 80 ) ),
	Column( 'TotalObligations', Float ),
	Column( 'UnliquidatedObligations', Float ),
	Column( 'ObligationsPaid', Float ) )

fund_categories = Table( 'FundCategories', metadata,
	Column( 'FundCategoriesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'ShortName', String( 80 ) ) )

carryover_apportionments = Table( 'CarryoverApportionments', metadata,
	Column( 'CarryoverApportionmentsId', Integer( ), primary_key=True ),
	Column( 'BudgetAccount', String( 80 ) ),
	Column( 'TreasuryAccount', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'Group', String( 80 ) ),
	Column( 'Description', String( 80 ) ),
	Column( 'LineName', String( 80 ) ),
	Column( 'AuthorityType', String( 80 ) ),
	Column( 'Request', Float ),
	Column( 'Balance', Float ),
	Column( 'Deobligations', Float ),
	Column( 'Amount', Float ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'LineSplit', String( 80 ) ),
	Column( 'ApportionmentAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

compass_levels = Table( 'CompassLevels', metadata,
	Column( 'CompassLevelsId', Integer( ), primary_key=True ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'AppropriationName', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentDate', DateTime ),
	Column( 'Authority', Float ),
	Column( 'CarryoverIn', Float ),
	Column( 'CarryoverOut', Float ),
	Column( 'Recoveries', Float ),
	Column( 'Reimbursements', Float ),
	Column( 'TreasuryAccountCode', Float ),
	Column( 'TreasuryAccountName', Float ),
	Column( 'BudgetAccountCode', Float ),
	Column( 'BudgetAccountName', Float ) )

allowance_holders = Table( 'AllowanceHolders', metadata,
	Column( 'AllowanceHoldersId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

annual_carryover_estimates = Table( 'AnnualCarryoverEstimates', metadata,
	Column( 'AnnualCarryoverEstimatesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Available', Float ),
	Column( 'Estimate', Float ) )

annual_reimbursable_estimates = Table( 'AnnualReimbursableEstimates', metadata,
	Column( 'AnnualReimbursableEstimatesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Available', Float ),
	Column( 'Estimate', Float ) )

budget_object_classes = Table( 'BudgetObjectClasses', metadata,
	Column( 'BudgetObjectClassesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

accounts = Table( 'Accounts', metadata,
	Column( 'AccountsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'GoalCode', String( 80 ) ),
	Column( 'ObjectiveCode', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'ActivityCode', String( 80 ) ),
	Column( 'ActivityName', String( 80 ) ),
	Column( 'AgencyActivity', String( 80 ) ) )

activity_codes = Table( 'ActivityCodes', metadata,
	Column( 'ActivityCodesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'Description', String( 80 ) ) )

capital_planning_investment_codes = Table( 'CapitalPlanningInvestmentCodes', metadata,
	Column( 'CapitalPlanningInvestmentCodesId', Integer( ), primary_key=True ),
	Column( 'Type', String( 80 ) ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

congressional_controls = Table( 'CongressionalControls', metadata,
	Column( 'CongressionalControlsId', Integer( ), primary_key=True ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'SubProjectCode', String( 80 ) ),
	Column( 'SubProjectName', String( 80 ) ),
	Column( 'ReprogrammingRestriction', String( 80 ) ),
	Column( 'IncreaseRestriction', String( 80 ) ),
	Column( 'DecreaseRestriction', String( 80 ) ),
	Column( 'MemoRequirement', String( 80 ) ) )

cost_areas = Table( 'CostAreas', metadata,
	Column( 'CostAreasId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

defactos = Table( 'Defactos', metadata,
	Column( 'DefactosId', Integer( ), primary_key=True ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

documents = Table( 'Documents', metadata,
	Column( 'DocumentsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Category', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'System', String( 80 ) ) )

federal_holidays = Table( 'FederalHolidays', metadata,
	Column( 'FederalHolidaysId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'Columbus', DateTime ),
	Column( 'Veterans', DateTime ),
	Column( 'Thanksgiving', DateTime ),
	Column( 'Christmas', DateTime ),
	Column( 'NewYears', DateTime ),
	Column( 'MartinLutherKing', DateTime ),
	Column( 'Washingtons', DateTime ),
	Column( 'Memorial', DateTime ),
	Column( 'Juneteenth', DateTime ),
	Column( 'Independence', DateTime ),
	Column( 'Labor', Date ) )

budget_fiscal_years = Table( 'BudgetFiscalYears', metadata,
	Column( 'BudgetFiscalYearsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'StartDate', DateTime ),
	Column( 'EndDate', DateTime ),
	Column( 'Columbus', DateTime ),
	Column( 'Christmas', DateTime ),
	Column( 'Thanksgiving', DateTime ),
	Column( 'Veterans', DateTime ),
	Column( 'Labor', DateTime ),
	Column( 'Independence', DateTime ),
	Column( 'Juneteenth', DateTime ),
	Column( 'Memorial', DateTime ),
	Column( 'Washingtons', DateTime ),
	Column( 'MartinLutherKing', DateTime ),
	Column( 'NewYears', DateTime ),
	Column( 'ExpiringYear', DateTime ),
	Column( 'ExpirationDate', DateTime ),
	Column( 'CancellationDate', DateTime ),
	Column( 'WorkDays', Float ),
	Column( 'WeekDays', Float ),
	Column( 'WeekEnds', Float ),
	Column( 'Availability', Float ) )

finance_object_classes = Table( 'FinanceObjectClasses', metadata,
	Column( 'FinanceObjectClassesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ) )

full_time_equivalents = Table( 'FullTimeEquivialents', metadata,
	Column( 'FullTimeEquivialentsId', Integer( ), primary_key=True ),
	Column( 'OperatingPlansId', Integer( ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'ITProjectCode', String( 80 ) ),
	Column( 'ProjectCode', String( 80 ) ),
	Column( 'ProjectName', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'ProjectTypeName', String( 80 ) ),
	Column( 'ProjectTypeCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ActivityCode', String( 80 ) ),
	Column( 'ActivityName', String( 80 ) ),
	Column( 'LocalCode', String( 80 ) ),
	Column( 'LocalCodeName', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'CostAreaCode', String( 80 ) ),
	Column( 'CostAreaName', String( 80 ) ),
	Column( 'GoalCode', String( 80 ) ),
	Column( 'GoalName', String( 80 ) ),
	Column( 'ObjectiveCode', String( 80 ) ),
	Column( 'ObjectiveName', String( 80 ) ) )

headquarters_offices = Table( 'HeadquartersOffices', metadata,
	Column( 'HeadquartersOfficesId', Integer( ), primary_key=True ),
	Column( 'ResourcePlanningOfficesId', Integer( ) ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

general_ledger_accounts = Table( 'GeneralLedgerAccounts', metadata,
	Column( 'GeneralLedgerAccountsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'AccountNumber', String( 80 ) ),
	Column( 'AccountName', String( 80 ) ),
	Column( 'BeginningBalance', Float ),
	Column( 'CreditBalance', Float ),
	Column( 'DebitBalance', Float ),
	Column( 'ClosingAmount', Float ) )

national_programs = Table( 'NationalPrograms', metadata,
	Column( 'NationalProgramsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'Title', String( 80 ) ) )

operating_plans = Table( 'OperatingPlans', metadata,
	Column( 'OperatingPlansId', Integer( ), primary_key=True ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ActivityCode', String( 80 ) ),
	Column( 'ActivityName', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'GoalCode', String( 80 ) ),
	Column( 'GoalName', String( 80 ) ),
	Column( 'ObjectiveCode', String( 80 ) ),
	Column( 'ObjectiveName', String( 80 ) ) )

program_areas = Table( 'ProgramAreas', metadata,
	Column( 'ProgramAreasId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

program_projects = Table( 'ProgramProjects', metadata,
	Column( 'ProgramProjectsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ) )

projects = Table( 'Projects', metadata,
	Column( 'ProjectsId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

public_laws = Table( 'PublicLaws', metadata,
	Column( 'PublicLawsId', Integer( ), primary_key=True ),
	Column( 'LawNumber', String( 80 ) ),
	Column( 'BillTitle', String( 80 ) ),
	Column( 'EnactedDate', DateTime ),
	Column( 'Congress', String( 80 ) ),
	Column( 'BFY', String( 80 ) ) )

resource_planning_offices = Table( 'ResourcePlanningOffices', metadata,
	Column( 'ResourcePlanningOfficesId', Integer( ), primary_key=True ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

regional_offices = Table( 'RegionalOffices', metadata,
	Column( 'RegionalOfficesId', Integer( ), primary_key=True ),
	Column( 'ResourcePlanningOfficesId', Integer( ) ),
	Column( 'Code', String( 80 ) ),
	Column( 'Name', String( 80 ) ) )

reimbursable_funds = Table( 'ReimbursableFunds', metadata,
	Column( 'ReimbursableFundsId', Integer( ), primary_key=True ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'AgreeementNumber', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'ULO', Float ),
	Column( 'Available', Float ) )

status_of_special_account_funds = Table( 'StatusOfSpecialAccountFunds', metadata,
	Column( 'StatusOfSpecialAccountFundsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'SpecialAccountFund', String( 80 ) ),
	Column( 'SpecialAccountNumber', String( 80 ) ),
	Column( 'SpecialAccountName', String( 80 ) ),
	Column( 'AccountStatus', String( 80 ) ),
	Column( 'NplStatusCode', String( 80 ) ),
	Column( 'NplStatusName', String( 80 ) ),
	Column( 'SiteId', String( 80 ) ),
	Column( 'CerclisId', String( 80 ) ),
	Column( 'SiteCode', String( 80 ) ),
	Column( 'SiteName', String( 80 ) ),
	Column( 'OperableUnit', String( 80 ) ),
	Column( 'PipelineCode', String( 80 ) ),
	Column( 'PipelineDescription', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'TransactionType', String( 80 ) ),
	Column( 'TransactionTypeName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'TransactionDate', DateTime ),
	Column( 'AvailableBalance', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'ULO', Float ),
	Column( 'Disbursements', Float ),
	Column( 'UnpaidBalances', Float ),
	Column( 'Collections', Float ),
	Column( 'CumulativeReceipts', Float ) )

status_of_superfund_sites = Table( 'StatusOfSuperfundSites', metadata,
	Column( 'SuperfundSitesId', Integer( ), primary_key=True ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'City', String( 80 ) ),
	Column( 'State', String( 80 ) ),
	Column( 'SSID', String( 80 ) ),
	Column( 'SiteProjectName', String( 80 ) ),
	Column( 'EpaSiteId', String( 80 ) ) )

trasntypes = Table( 'TransTypes', metadata,
	Column( 'TransTypesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'DocType', String( 80 ) ),
	Column( 'AppropriationBill', String( 80 ) ),
	Column( 'ContinuingResolution', String( 80 ) ),
	Column( 'RescissionCurrentYear', String( 80 ) ),
	Column( 'RescissionPriorYear', String( 80 ) ),
	Column( 'SequesterReduction', String( 80 ) ),
	Column( 'SequesterReturn', String( 80 ) ) )

appropriation_available_balances = Table( 'AppropriationAvailableBalances', metadata,
	Column( 'AppropriationAvailableBalancesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'OriginalAmount', Float ),
	Column( 'Authority', Float ),
	Column( 'Budgeted', Float ),
	Column( 'CarryoverIn', Float ),
	Column( 'CarryoverOut', Float ),
	Column( 'Reimbursements', Float ),
	Column( 'Recoveries', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ) )

obligation_activity = Table( 'ObligationActivity', metadata,
	Column( 'ObligationActivityId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'FocCode', String( 80 ) ),
	Column( 'FocName', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'UnliquidatedObligations', Float ),
	Column( 'Outlays', Float ) )

transfer_activity = Table( 'TransferActivity', metadata,
	Column( 'TransferActivityId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'FromTo', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProcessedDate', DateTime ),
	Column( 'DocumentNumber', String( 80 ) ),
	Column( 'Net', Float ),
	Column( 'Amount', Float ) )

treasury_symbols = Table( 'TreasurySymbols', metadata,
	Column( 'TreasurySymbolsId', Integer( ), primary_key=True ),
	Column( 'ShortKey', String( 80 ) ),
	Column( 'AllocationTransferAgency', String( 80 ) ),
	Column( 'AgencyIdentifier', String( 80 ) ),
	Column( 'BeginningPeriodOfAvailability', String( 80 ) ),
	Column( 'EndingPeriodOfAvailability', String( 80 ) ),
	Column( 'AvailabilityType', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'SubAccount', String( 80 ) ),
	Column( 'Lapsed', String( 80 ) ),
	Column( 'UseCancelledYearSpendingAccounts', String( 80 ) ),
	Column( 'AgencyTreasurySymbol', String( 80 ) ),
	Column( 'InUse', String( 80 ) ),
	Column( 'PreventNewUse', String( 80 ) ),
	Column( 'Status', String( 80 ) ) )

carryover_requests = Table( 'CarryoverRequests', metadata,
	Column( 'CarryoverRequestsId', Integer( ), primary_key=True ),
	Column( 'Analyst', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'DocumentTitle', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'Status', String( 80 ) ),
	Column( 'OriginalRequestDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'BudgetFormulationSystem', String( 80 ) ),
	Column( 'Comments', String( 80 ) ),
	Column( 'RequestDocument', String( 80 ) ),
	Column( 'Duration', Float ) )

congressional_projects = Table( 'CongressionalProjects', metadata,
	Column( 'CongressionalProjectsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'StateCode', String( 80 ) ),
	Column( 'StateName', String( 80 ) ),
	Column( 'Project', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

budget_contacts = Table( 'BudgetContacts', metadata,
	Column( 'ContactsId', Integer( ), primary_key=True ),
	Column( 'FirstName', String( 80 ) ),
	Column( 'LastName', String( 80 ) ),
	Column( 'FullName', String( 80 ) ),
	Column( 'EmailAddress', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'Section', String( 80 ) ) )

headquarters_authority = Table( 'HeadquartersAuthority', metadata,
	Column( 'HeadquartersAuthorityId', Integer( ), primary_key=True ),
	Column( 'AllocationsId', Integer( ) ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

regional_authority = Table( 'RegionalAuthority', metadata,
	Column( 'RegionalAuthorityId', Integer( ), primary_key=True ),
	Column( 'AllocationsId', Integer( ) ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

pay_periods = Table( 'PayPeriods', metadata,
	Column( 'PayPeriodsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'Period', String( 80 ) ),
	Column( 'StartDate', DateTime ),
	Column( 'EndDate', Date ) )

payroll_requests = Table( 'PayrollRequests', metadata,
	Column( 'PayrollRequestsId', Integer( ), primary_key=True ),
	Column( 'Analyst', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'DocumentTitle', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'Status', String( 80 ) ),
	Column( 'OriginalRequestDate', DateTime ),
	Column( 'LastActivityDate', DateTime ),
	Column( 'BudgetFormulationSystem', String( 80 ) ),
	Column( 'Comments', String( 80 ) ),
	Column( 'RequestDocument', String( 80 ) ),
	Column( 'Duration', Float ) )

status_of_budgetary_resources = Table( 'StatusOfBudgetaryResources', metadata,
	Column( 'StatusOfBudgetaryResourcesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'LastUpdate', DateTime ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BeginningPeriodOfAvailability', String( 80 ) ),
	Column( 'EndingPeriodOfAvailability', String( 80 ) ),
	Column( 'SectionNumber', String( 80 ) ),
	Column( 'SectionName', String( 80 ) ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'LineName', String( 80 ) ),
	Column( 'LineType', String( 80 ) ),
	Column( 'November', Float ),
	Column( 'December', Float ),
	Column( 'January', Float ),
	Column( 'Feburary', Float ),
	Column( 'April', Float ),
	Column( 'May', Float ),
	Column( 'June', Float ),
	Column( 'August', Float ),
	Column( 'September', Float ),
	Column( 'October', Float ),
	Column( 'LastUpdate', Date ) )

supplemental_carryover_estimates = Table( 'SupplementalCarryoverEstimates', metadata,
	Column( 'SupplementalCarryoverEstimatesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Available', Float ),
	Column( 'Estimate', Float ) )

spending_documents = Table( 'SpendingDocuments', metadata,
	Column( 'SpendingDocumentsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'TreasurySymbol', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'RpioActivityCode', String( 80 ) ),
	Column( 'RpioActivityName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'PurchaseRequestNumber', String( 80 ) ),
	Column( 'DocumentType', String( 80 ) ),
	Column( 'DocumentControlNumber', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'OriginalActionDate', DateTime ),
	Column( 'LastActionDate', DateTime ),
	Column( 'Commitmets', Float ),
	Column( 'Obligations', Float ),
	Column( 'Deobligations', Float ),
	Column( 'UnliquidatedObligations', Float ) )

column_schema = Table( 'ColumnSchema', metadata,
	Column( 'ColumnSchemaId', Integer( ), primary_key=True ),
	Column( 'DataType', String( 80 ) ),
	Column( 'ColumnName', String( 80 ) ),
	Column( 'TableName', String( 80 ) ),
	Column( 'ColumnCaption', String( 80 ) ) )

spending_rates = Table( 'SpendingRates', metadata,
	Column( 'SpendingRatesId', Integer( ), primary_key=True ),
	Column( 'OmbAgencyCode', String( 80 ) ),
	Column( 'OmbAgencyName', String( 80 ) ),
	Column( 'OmbBureauCode', String( 80 ) ),
	Column( 'OmbBureauName', String( 80 ) ),
	Column( 'TreausuryAgencyCode', String( 80 ) ),
	Column( 'TreausuryAccountCode', String( 80 ) ),
	Column( 'TreausuryAccountName', String( 80 ) ),
	Column( 'AccountTitle', String( 80 ) ),
	Column( 'Subfunction', String( 80 ) ),
	Column( 'Line', String( 80 ) ),
	Column( 'LineNumber', String( 80 ) ),
	Column( 'Category', String( 80 ) ),
	Column( 'Subcategory', String( 80 ) ),
	Column( 'SubcategoryName', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'Jurisdiction', String( 80 ) ),
	Column( 'YearOfAuthority', String( 80 ) ),
	Column( 'BudgetAuthority', Float ),
	Column( 'OutYear1', Float ),
	Column( 'OutYear2', Float ),
	Column( 'OutYear3', Float ),
	Column( 'OutYear4', Float ),
	Column( 'OutYear5', Float ),
	Column( 'OutYear6', Float ),
	Column( 'OutYear7', Float ),
	Column( 'OutYear8', Float ),
	Column( 'OutYear9', Float ),
	Column( 'OutYear10', Float ),
	Column( 'OutYear11', Float ),
	Column( 'TotalSpendout', Float ) )

resources = Table( 'Resources', metadata,
	Column( 'ResourcesId', Integer( ), primary_key=True ),
	Column( 'Identifier', String( 80 ) ),
	Column( 'Type', String( 80 ) ),
	Column( 'Location', String( 80 ) ),
	Column( 'FileExtension', String( 80 ) ),
	Column( 'Caption', String( 80 ) ) )

budget_documents = Table( 'BudgetDocuments', metadata,
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

allocations = Table( 'Allocations', metadata,
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

inflation_reduction_act_carryover = Table( 'InflationReductionActCarryoverEstimates', metadata,
	Column( 'InflationReductionActCarryoverEstimatesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Available', Float ),
	Column( 'Estimate', Float ) )

american_rescue_plan_carryover = Table( 'AmericanRescuePlanCarryoverEstimates', metadata,
	Column( 'AmericanRescuePlanCarryoverEstimatesId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'Obligations', Float ),
	Column( 'Available', Float ),
	Column( 'Estimate', Float ) )

monthly_actuals = Table( 'MonthlyActuals', metadata,
	Column( 'MonthlyActualsId', Integer( ), primary_key=True ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'AppropriationCode', String( 80 ) ),
	Column( 'AppropriationName', String( 80 ) ),
	Column( 'SubAppropriationCode', String( 80 ) ),
	Column( 'SubAppropriationName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'RpioActivityCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'Obligations', Float ),
	Column( 'GrossOutlays', Float ),
	Column( 'NetOutlays', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ) )

pay_periods = Table( 'PayPeriods', metadata,
	Column( 'Number', String( 80 ) ),
	Column( 'Type', String( 80 ) ),
	Column( 'SecurityOrg', String( 80 ) ),
	Column( 'SplitPayPeriod', String( 80 ) ) )

operating_plans = Table( 'OperatingPlans', metadata,
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'Version', String( 80 ) ) )

status_of_american_rescue_plan = Table( 'StatusOfAmericanRescuePlanFunds', metadata,
	Column( 'StatusOfAmericanResuePlanFundsId', Integer( ), primary_key=True ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

status_of_inflation_reduction_act = Table( 'StatusOfInflationReductionActFunds', metadata,
	Column( 'StatusOfInflationReductionActFundsId', Integer( ), primary_key=True ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'LowerName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'Budgeted', Float ),
	Column( 'Posted', Float ),
	Column( 'OpenCommitments', Float ),
	Column( 'ULO', Float ),
	Column( 'Expenditures', Float ),
	Column( 'Obligations', Float ),
	Column( 'Used', Float ),
	Column( 'Available', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

aggregate_outlays = Table( 'AggregateOutlays', metadata,
	Column( 'AggregateOutlaysId', Integer( ), primary_key=True ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'October', Float ),
	Column( 'November', Float ),
	Column( 'December', Float ),
	Column( 'January', Float ),
	Column( 'Feburary', Float ),
	Column( 'March', Float ),
	Column( 'April', Float ),
	Column( 'May', Float ),
	Column( 'June', Float ),
	Column( 'July', Float ),
	Column( 'August', Float ),
	Column( 'September', Float ) )

marginal_outlays = Table( 'MarginalOutlays', metadata,
	Column( 'MarginalOutlaysId', Integer( ), primary_key=True ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'MainAccount', String( 80 ) ),
	Column( 'October', Float ),
	Column( 'November', Float ),
	Column( 'December', Float ),
	Column( 'January', Float ),
	Column( 'Feburary', Float ),
	Column( 'March', Float ),
	Column( 'April', Float ),
	Column( 'May', Float ),
	Column( 'June', Float ),
	Column( 'July', Float ),
	Column( 'August', Float ),
	Column( 'September', Float ) )

outlay_rates = Table( 'OutlayRates', metadata,
	Column( 'OutlayRatesId', Integer( ), primary_key=True ),
	Column( 'FiscalYear', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ),
	Column( 'Category', String( 80 ) ),
	Column( 'Baseline', String( 80 ) ),
	Column( 'Year1', Float ),
	Column( 'Year2', Float ),
	Column( 'Year3', Float ),
	Column( 'Year4', Float ),
	Column( 'Year5', Float ),
	Column( 'Year6', Float ),
	Column( 'Year7', Float ),
	Column( 'Year8', Float ),
	Column( 'Year9', Float ),
	Column( 'Year10', Float ),
	Column( 'Year11', Float ) )

combined_schedules = Table( 'CombinedSchedules', metadata,
	Column( 'CombinedSchedulesId ', Integer( ), primary_key=True ),
	Column( 'ReportingYear ', String( 80 ) ),
	Column( 'MainAccount ', String( 80 ) ),
	Column( 'LineNumber ', String( 80 ) ),
	Column( 'LineName ', String( 80 ) ),
	Column( 'SplitNumber ', String( 80 ) ),
	Column( 'PriorYear ', Float ),
	Column( 'CurrentYear ', Float ),
	Column( 'BudgetYear ', Float ),
	Column( 'BudgetYear1 ', Float ),
	Column( 'BudgetYear2 ', Float ),
	Column( 'BudgetYear3 ', Float ),
	Column( 'BudgetYear4 ', Float ),
	Column( 'BudgetYear5 ', Float ),
	Column( 'BudgetYear6 ', Float ),
	Column( 'BudgetYear7 ', Float ),
	Column( 'BudgetYear8 ', Float ),
	Column( 'BudgetYear9 ', Float ),
	Column( 'AccountName ', String( 80 ) ),
	Column( 'TreasuryAccount ', String( 80 ) ),
	Column( 'Subfunction ', String( 80 ) ),
	Column( 'Classification ', String( 80 ) ),
	Column( 'BudgetEnforcementCategory', String( 80 ) ) )

status_of_budgetary_resources = Table( 'StatusOfBudgetaryResources', metadata,
	Column( 'StatusOfBudgetaryResourcesId ', Integer( ), primary_key=True ),
	Column( 'BFY ', String( 80 ) ),
	Column( 'TreasuryAccountCode ', String( 80 ) ),
	Column( 'TreasuryAccountName ', String( 80 ) ),
	Column( 'BudgetAccountName ', String( 80 ) ),
	Column( 'BudgetAccountCode ', String( 80 ) ),
	Column( 'BeginningPeriodOfAvailability ', String( 80 ) ),
	Column( 'EndingPeriodOfAvailability ', String( 80 ) ),
	Column( 'SectionNumber ', String( 80 ) ),
	Column( 'SectionName ', String( 80 ) ),
	Column( 'LineNumber ', String( 80 ) ),
	Column( 'LineName ', String( 80 ) ),
	Column( 'November ', Float ),
	Column( 'December ', Float ),
	Column( 'January ', Float ),
	Column( 'Feburary ', Float ),
	Column( 'March ', Float ),
	Column( 'May ', Float ),
	Column( 'June ', Float ),
	Column( 'July ', Float ),
	Column( 'August ', Float ),
	Column( 'September ', Float ),
	Column( 'October ', Float ),
	Column( 'LastUpdate', String( 80 ) ) )

status_of_budget_execution = Table( 'StatusOfBudgetExecution', metadata,
	Column( 'StatusOfBudgetExecutionId ', Integer( ), primary_key=True ),
	Column( 'LineCaption ', String( 80 ) ),
	Column( 'LineName', String( 80 ) ),
	Column( 'LineNumber ', String( 80 ) ),
	Column( 'Amount ', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

main_accounts = Table( 'MainAccounts', metadata,
	Column( 'MainAccountsId ', Integer( ), primary_key=True ),
	Column( 'Code ', String( 80 ) ),
	Column( 'Name ', String( 80 ) ),
	Column( 'BudgetAccountCode ', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

earmark_accounts = Table( 'EarmarkAccounts', metadata,
	Column( 'EarmarkAccountsId', Integer( ), primary_key=True ),
	Column( 'BFY  ', String( 80 ) ),
	Column( 'EFY  ', String( 80 ) ),
	Column( 'FundCode  ', String( 80 ) ),
	Column( 'FundName  ', String( 80 ) ),
	Column( 'RpioCode  ', String( 80 ) ),
	Column( 'RpioName  ', String( 80 ) ),
	Column( 'AhCode  ', String( 80 ) ),
	Column( 'AhName  ', String( 80 ) ),
	Column( 'NpmCode  ', String( 80 ) ),
	Column( 'NpmName  ', String( 80 ) ),
	Column( 'AccountCode  ', String( 80 ) ),
	Column( 'BocCode  ', String( 80 ) ),
	Column( 'BocName  ', String( 80 ) ),
	Column( 'ProgramProjectCode  ', String( 80 ) ),
	Column( 'ProgramProjectName  ', String( 80 ) ),
	Column( 'ProgramAreaCode  ', String( 80 ) ),
	Column( 'ProgramAreaName  ', String( 80 ) ),
	Column( 'StateCode  ', String( 80 ) ),
	Column( 'StateName  ', String( 80 ) ),
	Column( 'Project  ', String( 80 ) ),
	Column( 'Amount ', Float ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )

payroll_authority = Table( 'PayrollAuthority', metadata,
	Column( 'PayrollAuthorityId', Integer( ), primary_key=True ),
	Column( 'AllocationsId', Integer( ) ),
	Column( 'StatusOfFundsId', Integer( ) ),
	Column( 'BudgetLevel', String( 80 ) ),
	Column( 'BFY', String( 80 ) ),
	Column( 'EFY', String( 80 ) ),
	Column( 'RpioCode', String( 80 ) ),
	Column( 'RpioName', String( 80 ) ),
	Column( 'AhCode', String( 80 ) ),
	Column( 'AhName', String( 80 ) ),
	Column( 'FundCode', String( 80 ) ),
	Column( 'FundName', String( 80 ) ),
	Column( 'OrgCode', String( 80 ) ),
	Column( 'OrgName', String( 80 ) ),
	Column( 'AccountCode', String( 80 ) ),
	Column( 'BocCode', String( 80 ) ),
	Column( 'BocName', String( 80 ) ),
	Column( 'ProgramProjectCode', String( 80 ) ),
	Column( 'ProgramProjectName', String( 80 ) ),
	Column( 'ProgramAreaCode', String( 80 ) ),
	Column( 'ProgramAreaName', String( 80 ) ),
	Column( 'RcCode', String( 80 ) ),
	Column( 'RcName', String( 80 ) ),
	Column( 'Amount', Float ),
	Column( 'NpmCode', String( 80 ) ),
	Column( 'NpmName', String( 80 ) ),
	Column( 'TreasuryAccountCode', String( 80 ) ),
	Column( 'TreasuryAccountName', String( 80 ) ),
	Column( 'BudgetAccountCode', String( 80 ) ),
	Column( 'BudgetAccountName', String( 80 ) ) )
