CREATE TABLE AppropriationBills
(
   ID INTEGER NOT NULL UNIQUE,
   BFY TEXT(80) NULL DEFAULT NS,
   Title TEXT(80) DEFAULT NS,
   PublicLaw TEXT(80) DEFAULT NS,
   EnactedDate TEXT(80) DEFAULT NS
);
