CREATE TABLE BudgetControls
(
    BudgetControlsId AUTOINCREMENT NOT NULL UNIQUE,
    Code TEXT(80) NULL DEFAULT NS,
    Name TEXT(80) NULL DEFAULT NS,
    SecOrg. TEXT(80) NULL DEFAULT NS,
    BdgtTransType TEXT(80) NULL DEFAULT NS,
    PstdTransType TEXT(80) NULL DEFAULT NS,
    EstReimTransType TEXT(80) NULL DEFAULT NS,
    SpngAdjTransType TEXT(80) NULL DEFAULT NS,
    EstRecTransType TEXT(80) NULL DEFAULT NS,
    ActlRecTransType TEXT(80) NULL DEFAULT NS,
    StatRsrvTransType TEXT(80) NULL DEFAULT NS,
    ProfLossTransType TEXT(80) NULL DEFAULT NS,
    EstReimSpngOpt TEXT(80) NULL DEFAULT NS,
    EstReimBdgtOpt TEXT(80) NULL DEFAULT NS,
    TrckAgreLowerLevel TEXT(80) NULL DEFAULT NS,
    BdgtEstLowerLevel TEXT(80) NULL DEFAULT NS,
    EstRecSpngOpt TEXT(80) NULL DEFAULT NS,
    EstRecBdgtOpt TEXT(80) NULL DEFAULT NS,
    RecNextLevel TEXT(80) NULL DEFAULT NS,
    RecBdgtMismatch TEXT(80) NULL DEFAULT NS,
    Profit/LossSpngOpt TEXT(80) NULL DEFAULT NS,
    Profit/LossBdgtOpt TEXT(80) NULL DEFAULT NS,
    RecCrryInLowerLevel TEXT(80) NULL DEFAULT NS,
    RecCrryInLowerLevelCtrl TEXT(80) NULL DEFAULT NS,
    RecCrryInAMCtrl TEXT(80) NULL DEFAULT NS,
    BdgtCtrl TEXT(80) NULL DEFAULT NS,
    PstdCtrl TEXT(80) NULL DEFAULT NS,
    PreCommSpngCtrl TEXT(80) NULL DEFAULT NS,
    CommSpngCtrl TEXT(80) NULL DEFAULT NS,
    ObligSpngCtrl TEXT(80) NULL DEFAULT NS,
    AccrSpngCtrl TEXT(80) NULL DEFAULT NS,
    ExpndSpngCtrl TEXT(80) NULL DEFAULT NS,
    ExpnsSpngCtrl TEXT(80) NULL DEFAULT NS,
    ReimSpngCtrl TEXT(80) NULL DEFAULT NS,
    ReimAgreSpngCtrl TEXT(80) NULL DEFAULT NS,
    FteBdgtCtrl TEXT(80) NULL DEFAULT NS,
    FteSpngCtrl TEXT(80) NULL DEFAULT NS,
    TransactionTypeCtrl TEXT(80) NULL DEFAULT NS,
    AuthorityDistributionCtrl TEXT(80) NULL DEFAULT NS,
    CONSTRAINT BudgetControlsPrimaryKey
        PRIMARY KEY(BudgetControlsId)
);
