CREATE TABLE CompassLevels 
(
    CompassLevelsId AUTOINCREMENT NOT NULL UNIQUE,
    BudgetLevel TEXT(80) NULL DEFAULT NS,
    BFY TEXT(80) NULL DEFAULT NS,
    EFY TEXT(80) NULL DEFAULT NS,
    FundCode TEXT(80) NULL DEFAULT NS,
    FundName TEXT(80) NULL DEFAULT NS,
    AppropriationCode TEXT(80) NULL DEFAULT NS,
    SubAppropriationCode TEXT(80) NULL DEFAULT NS,
    AppropriationName TEXT(80) NULL DEFAULT NS,
    TreasurySymbol TEXT(80) NULL DEFAULT NS,
    DocumentType TEXT(80) NULL DEFAULT NS,
    LowerName TEXT(80) NULL DEFAULT NS,
    PostedControlFlag TEXT(80) NULL DEFAULT NS,
    ActualRecoveryTransType TEXT(80) NULL DEFAULT NS,
    CommitmentSpendControlFlag TEXT(80) NULL DEFAULT NS,
    BudgetDefault TEXT(80) NULL DEFAULT NS,
    LowerChildExpendSpendCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerChildExpenseSpendCtrlFlag TEXT(80) NULL DEFAULT NS,
    FteControlFlag TEXT(80) NULL DEFAULT NS,
    AccrualSpendingControlFlag TEXT(80) NULL DEFAULT NS,
    ObligationSpendingControlFlag TEXT(80) NULL DEFAULT NS,
    PreCommitmentSpendingControlFlag TEXT(80) NULL DEFAULT NS,
    LowerCommSpendCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerObligSpendCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerExpenditureSpendingCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerExpenseSpendingCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerPostedCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerPostedTransType TEXT(80) NULL DEFAULT NS,
    LowerTransType TEXT(80) NULL DEFAULT NS,
    LowerPostedFlag TEXT(80) NULL DEFAULT NS,
    LowerPreCommSpendCtrlFlag TEXT(80) NULL DEFAULT NS,
    LowerRecoveriesSpendingOption TEXT(80) NULL DEFAULT NS,
    LowerRecoveriesOption TEXT(80) NULL DEFAULT NS,
    LowerReimbSpendingOption TEXT(80) NULL DEFAULT NS,
    Date TEXT(80) NULL DEFAULT NS,
    TotalAuthority DECIMAL NULL DEFAULT 0.0,
    OriginalAmount DECIMAL NULL DEFAULT 0.0,
    CarryoverAvailabilityPercentage DECIMAL NULL DEFAULT 0.0,
    CarryIn DECIMAL NULL DEFAULT 0.0,
    CarryOut DECIMAL NULL DEFAULT 0.0,
    FundsIn DECIMAL NULL DEFAULT 0.0,
    FundOut DECIMAL NULL DEFAULT 0.0,
    RecoveriesWithdrawn DECIMAL NULL DEFAULT 0.0,
    ActualRecoveries DECIMAL NULL DEFAULT 0.0,
    ActualReimbursements DECIMAL NULL DEFAULT 0.0,
    AgreementReimbursables DECIMAL NULL DEFAULT 0.0,
    CONSTAINT CompassLevelsPrimaryKey
        PRIMARY KEY(CompassLevelsId)
);