CREATE TABLE GrowthRates 
(
 GrowthRatesId AUTOINCREMENT NOT NULL UNIQUE,
 RateId TEXT(80) NULL DEFAULT NS,
 DESCRIPTION TEXT(255) NULL DEFAULT NS,
 BudgetYearRate DECIMAL NULL DEFAULT 0.0,
 OutYear1 DECIMAL NULL DEFAULT 0.0,
 OutYear2 DECIMAL NULL DEFAULT 0.0,
 OutYear3 DECIMAL NULL DEFAULT 0.0,
 OutYear4 DECIMAL NULL DEFAULT 0.0,
 OutYear5 DECIMAL NULL DEFAULT 0.0,
 OutYear6 DECIMAL NULL DEFAULT 0.0,
 OutYear7 DECIMAL NULL DEFAULT 0.0,
 OutYear8 DECIMAL NULL DEFAULT 0.0,
 OutYear9 DECIMAL NULL DEFAULT 0.0,
 Sort TEXT(80) NULL DEFAULT NS,
 CONSTRAINT GrowthRatesPrimaryKey
    PRIMARY KEY(GrowthRatesId)
);