CREATE TABLE StatusOfSupplementalFunding 
(
    StatusOfSupplementalFunding AUTOINCREMENT NOT NULL UNIQUE,
    StatusOfFundsId INTEGER NOT NULL,
    BudgetLevel TEXT DEFAULT NS,
    BFY TEXT DEFAULT NS,
    EFY TEXT DEFAULT NS,
    RpioCode TEXT DEFAULT NS,
    RpioName TEXT DEFAULT NS,
    AhCode TEXT DEFAULT NS,
    AhName TEXT DEFAULT NS,
    FundCode TEXT DEFAULT NS,
    FundName TEXT DEFAULT NS,
    OrgCode TEXT DEFAULT NS,
    OrgName TEXT DEFAULT NS,
    AccountCode TEXT DEFAULT NS,
    BocCode TEXT DEFAULT NS,
    BocName TEXT DEFAULT NS,
    ProgramProjectCode TEXT DEFAULT NS,
    ProgramProjectName TEXT DEFAULT NS,
    ProgramAreaCode TEXT DEFAULT NS,
    ProgramAreaName TEXT DEFAULT NS,
    RcCode TEXT DEFAULT NS,
    RcName TEXT DEFAULT NS,
    LowerName TEXT DEFAULT NS,
    Amount DECIMAL NULL DEFAULT 0.0,
    Budgeted DECIMAL NULL DEFAULT 0.0,
    Posted DECIMAL NULL DEFAULT 0.0,
    OpenCommitments DECIMAL NULL DEFAULT 0.0,
    ULO DECIMAL NULL DEFAULT 0.0,
    Expenditures DECIMAL NULL DEFAULT 0.0,
    Obligations DECIMAL NULL DEFAULT 0.0,
    Used DECIMAL NULL DEFAULT 0.0,
    Available DECIMAL NULL DEFAULT 0.0,
    NpmCode TEXT DEFAULT NS,
    NpmName TEXT DEFAULT NS,
    CONSTRAINT StatusOfSupplementalFundingPrimaryKey
        PRIMARY KEY(SupplementalAuthorityId)
);

