CREATE TABLE IF NOT EXISTS 'BudgetResourceExecution' 
(
	'BudgetResourceExecutionId'	INTEGER NOT NULL,
	'FiscalYear' TEXT(80) DEFAULT 'NS',
	'Agency' TEXT(80) DEFAULT 'NS',
	'Bureau' TEXT(80) DEFAULT 'NS',
	'OmbAccount' TEXT(80) DEFAULT 'NS',
	'TreasuryAgencyCode' TEXT(80) DEFAULT 'NS',
	'TreasuryAccountCode' TEXT(80) DEFAULT 'NS',
	'BFY' TEXT(80) DEFAULT 'NS',
	'EFY' TEXT(80) DEFAULT 'NS',
	'STAT' TEXT(80) DEFAULT 'NS',
	'CreditIndicator' TEXT(80) DEFAULT 'NS',
	'LineNumber' TEXT(80) DEFAULT 'NS',
	'LineDescription' TEXT(80) DEFAULT 'NS',
	'TAFS' TEXT(80) DEFAULT 'NS',
	'AgencyTitle' TEXT(80) DEFAULT 'NS',
	'LastUpdate' TEXT(80) DEFAULT 'NS',
	'SectionName' TEXT(80) DEFAULT 'NS',
	'SectionNumber' TEXT(80) DEFAULT 'NS',
	'LineType' TEXT(80) DEFAULT 'NS',
	'TafsAccountCode' TEXT(80) DEFAULT 'NS',
	'BureauTitle' TEXT(80) DEFAULT 'NS',
	'OmbAccountCode' TEXT(80) DEFAULT 'NS',
	'FinancingAccounts' TEXT(80) DEFAULT 'NS',
	'November' NUMERIC DEFAULT 0.0,
	'January' NUMERIC DEFAULT 0.0,
	'Feburary' NUMERIC DEFAULT 0.0,
	'April' NUMERIC DEFAULT 0.0,
	'May' NUMERIC DEFAULT 0.0,
	'June' NUMERIC DEFAULT 0.0,
	'August' NUMERIC DEFAULT 0.0,
	'October' NUMERIC DEFAULT 0.0,
	'AMT1' NUMERIC DEFAULT 0.0,
	'AMT2' NUMERIC DEFAULT 0.0,
	'AMT3' NUMERIC DEFAULT 0.0,
	'AMT4' NUMERIC DEFAULT 0.0,
	PRIMARY KEY('BudgetResourceExecutionId')
);