CREATE TABLE "Allocations" (
	"AllocationsId"	INTEGER NOT NULL UNIQUE,
	"StatusOfFundsId"	INTEGER NOT NULL,
	"BudgetLevel"	TEXT,
	"BFY"	TEXT,
	"EFY"	TEXT,
	"RpioCode"	TEXT,
	"RpioName"	TEXT,
	"AhCode"	TEXT,
	"AhName"	TEXT,
	"FundCode"	TEXT,
	"FundName"	TEXT,
	"OrgCode"	TEXT,
	"OrgName"	TEXT,
	"AccountCode"	TEXT,
	"BocCode"	TEXT,
	"BocName"	TEXT,
	"ProgramProjectCode"	TEXT,
	"ProgramProjectName"	TEXT,
	"ProgramAreaCode"	TEXT,
	"ProgramAreaName"	TEXT,
	"RcCode"	TEXT,
	"RcName"	TEXT,
	"LowerName"	TEXT,
	"Amount"	REAL,
	"Budgeted"	REAL,
	"Posted"	REAL,
	"OpenCommitments"	REAL,
	"ULO"	REAL,
	"Expenditures"	REAL,
	"Obligations"	REAL,
	"Used"	REAL,
	"Available"	REAL,
	"NpmCode"	TEXT,
	"NpmName"	TEXT,
	PRIMARY KEY("AllocationsId" AUTOINCREMENT)
)