CREATE TABLE IF NOT EXISTS EarmarkCodes
 (
	EarmarkCodesId INTEGER NOT NULL UNIQUE,
	BFY	 TEXT(80) NULL DEFAULT NS,
	RpioCode	 TEXT(80) NULL DEFAULT NS,
	AhCode	 TEXT(80) NULL DEFAULT NS,
	AhName	 TEXT(80) NULL DEFAULT NS,
	    PRIMARY KEY(EarmarkCodesId AUTOINCREMENT)
);