CREATE TABLE IF NOT EXISTS PRC 
(
	PrcId	INTEGER NOT NULL UNIQUE,
	StatusOfFundsId INTEGER NOT NULL,
	BFY	TEXT(80) NULL DEFAULT NS,
	EFY	TEXT(80) NULL DEFAULT NS,
	FundCode	TEXT(80) NULL DEFAULT NS,
	RpioCode	TEXT(80) NULL DEFAULT NS,
	AhCode	TEXT(80) NULL DEFAULT NS,
	OrgCode	TEXT(80) NULL DEFAULT NS,
	AccountCode	TEXT(80) NULL DEFAULT NS,
	BocCode	TEXT(80) NULL DEFAULT NS,
    PRIMARY KEY(PrcId AUTOINCREMENT)
);