CREATE TABLE IF NOT EXISTS "SpendingRates" 
(
	"SpendingRatesId"	INTEGER NOT NULL UNIQUE,
	"OmbAgencyCode"	TEXT DEFAULT 'NS',
	"OmbAgencyName"	TEXT DEFAULT 'NS',
	"OmbBureauCode"	TEXT DEFAULT 'NS',
	"OmbBureauName"	TEXT DEFAULT 'NS',
	"TreausuryAgencyCode"	TEXT DEFAULT 'NS',
	"TreausuryAccountCode"	TEXT DEFAULT 'NS',
	"TreausuryAccountName"	TEXT DEFAULT 'NS',
	"AccountTitle"	TEXT DEFAULT 'NS',
	"Subfunction"	TEXT DEFAULT 'NS',
	"Line"	TEXT DEFAULT 'NS',
	"LineNumber"	TEXT DEFAULT 'NS',
	"Category"	TEXT DEFAULT 'NS',
	"Subcategory"	TEXT DEFAULT 'NS',
	"SubcategoryName"	TEXT DEFAULT 'NS',
	"OmbAccountCode"	TEXT DEFAULT 'NS',
	"Jurisdiction"	TEXT DEFAULT 'NS',
	"YearOfAuthority"	TEXT DEFAULT 'NS',
	"BudgetAuthority"	NUMERIC DEFAULT 0,
	"OutYear1"	NUMERIC DEFAULT 0,
	"OutYear2"	NUMERIC DEFAULT 0,
	"OutYear3"	NUMERIC DEFAULT 0,
	"OutYear4"	NUMERIC DEFAULT 0,
	"OutYear5"	NUMERIC DEFAULT 0,
	"OutYear6"	NUMERIC DEFAULT 0,
	"OutYear7"	NUMERIC DEFAULT 0,
	"OutYear8"	NUMERIC DEFAULT 0,
	"OutYear9"	NUMERIC DEFAULT 0,
	"OutYear10"	NUMERIC DEFAULT 0,
	"OutYear11"	NUMERIC DEFAULT 0,
	"TotalSpendout"	NUMERIC DEFAULT 0,
	PRIMARY KEY("SpendingRatesId" AUTOINCREMENT)
);