CREATE TABLE Allocations
(
	    AllocationsId INTEGER NOT NULL UNIQUE CONSTRAINT PK_Allocations PRIMARY KEY,
        StatusOfFundsId INTEGER NOT NULL UNIQUE,
	    BudgetLevel TEXT(255) NULL,
	    RpioCode TEXT(255) NULL,
	    BFY TEXT(255) NULL,
	    EFY TEXT(255) NULL,
	    AhCode TEXT(255) NULL,
	    FundCode TEXT(255) NULL,
	    OrgCode TEXT(255) NULL,
	    AccountCode TEXT(255) NULL,
	    BocCode TEXT(255) NULL,
	    RcCode TEXT(255) NULL,
	    Amount DOUBLE NOT NULL,
	    RpioName TEXT(255) NULL,
	    FundName TEXT(255) NULL,
	    AhName TEXT(255) NULL,
	    BocName TEXT(255) NULL,
	    RcName TEXT(255) NULL,
	    OrgName TEXT(255) NULL,
	    NpmName TEXT(255) NULL,
	    NpmCode TEXT(255) NULL,
	    ProgramProjectCode TEXT(255) NULL,
	    ProgramProjectName TEXT(255) NULL,
	    ProgramAreaCode TEXT(255) NULL,
	    ProgramAreaName TEXT(255) NULL,
	    GoalCode TEXT(255) NULL,
	    GoalName TEXT(255) NULL,
	    ObjectiveCode TEXT(255) NULL,
	    ObjectiveName TEXT(255) NULL
);